version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-management-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - task-management-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-management-backend
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/task_management
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    ports:
      - "8080:8080"
    networks:
      - task-management-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-management-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - task-management-network

  redis:
    image: redis:7-alpine
    container_name: task-management-redis
    ports:
      - "6379:6379"
    networks:
      - task-management-network

volumes:
  mysql_data:

networks:
  task-management-network:
    driver: bridge